spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  data:
    mongodb:
      host: localhost
      port: 27017
      database: EducationalVideosStreamer
